apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: 9090
      targetPort: http
      name: http
  selector:
    {{- include "observability.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability.fullname" . }}-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
spec:
  type: {{ .Values.grafana.service.type }}
  ports:
    - port: 3000
      targetPort: http
      name: http
  selector:
    {{- include "observability.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability.fullname" . }}-loki
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
spec:
  type: {{ .Values.loki.service.type }}
  ports:
    - port: 3100
      targetPort: http
      name: http
  selector:
    {{- include "observability.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: loki
