apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: queue
  labels:
    app: kafka
  annotations:
    kubernetes.io/description: "Kafka configuration. Mount as server.properties if needed."
data:
  server.properties: |
    broker.id=1
    log.dirs=/var/lib/kafka
    zookeeper.connect=zookeeper.queue.svc.cluster.local:2181
    offsets.topic.replication.factor=1
    listeners=PLAINTEXT://:9092
    advertised.listeners=PLAINTEXT://kafka-0.kafka.queue.svc.cluster.local:9092,PLAINTEXT_HOST://localhost:9092 