apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: db
  labels:
    app: mysql
  annotations:
    kubernetes.io/description: "MySQL configuration. Mount as mysql_custom.cnf."
data:
  mysql_custom.cnf: |
    [mysqld]
    user=mysql
    bind-address=0.0.0.0
    port=3306
    sql_mode=STRICT_ALL_TABLES
    max_connections=200
    innodb_buffer_pool_size=256M 