apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
data:
  vault.hcl: |
    ui = true
    
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = {{ .Values.config.tlsDisable }}
    }
    
    storage "file" {
      path = "/vault/data"
    }
    
    {{- if .Values.config.telemetry.enabled }}
    telemetry {
      prometheus_retention_time = "30s"
      disable_hostname = true
    }
    {{- end }}
