version: '3.8'

services:
  # Vault Service
  vault:
    image: hashicorp/vault:1.18.3 # Use a specific version of Vault
    container_name: spring_boot_vault_container
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_LOCAL_CONFIG: |
        {
          "ui": true
        }
    cap_add:
      - IPC_LOCK
    networks:
      - app_network

networks:
  app_network: # Custom network for container communication (Optional but recommended)