apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-app.fullname" . }}-config
  labels:
    app: {{ include "helm-app.name" . }}
    environment: {{ .Values.env.ENVIRONMENT }}
data:
  ENVIRONMENT: {{ .Values.env.ENVIRONMENT | quote }} 