apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-app.fullname" . }}
  labels:
    app: {{ include "helm-app.name" . }}
    environment: {{ .Values.env.ENVIRONMENT }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ include "helm-app.name" . }}
    environment: {{ .Values.env.ENVIRONMENT }} 