version: '3'
services:
  redis-7000:
    image: redis:7.2
    container_name: redis-7000
    command: redis-server --port 7000 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports: [ "7000:7000" ]

  redis-7001:
    image: redis:7.2
    container_name: redis-7001
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports: [ "7001:7001" ]

  redis-7002:
    image: redis:7.2
    container_name: redis-7002
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports: [ "7002:7002" ]

  redis-7003:
    image: redis:7.2
    container_name: redis-7003
    command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports: [ "7003:7003" ]

  redis-7004:
    image: redis:7.2
    container_name: redis-7004
    command: redis-server --port 7004 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports: [ "7004:7004" ]

  redis-7005:
    image: redis:7.2
    container_name: redis-7005
    command: redis-server --port 7005 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports: [ "7005:7005" ]
